### ISSUE TITLE
ابزار نصب بالا نمیاد

### ISSUE THREAD

**Issue by RezaT1994** [pinoox/pinoox#24]
من میخوام روی لوکال هاست پینوکس رو بیارم بالا ولی نصب کننده اصلا نمیاد.
آدرس رو که میزنم صفحه سفید میاد

**Comment by esmaeilbahrani** [comment]
گزارش خطا و لاگ php و خطای کنسول مرورگر رو جهت بررسی بفرستین

**Comment by esmaeilbahrani** [comment]
> خطای کنسول مرورگر و لاگ
> php
> رو جهت بررسی بفرستین



> من میخوام روی لوکال هاست پینوکس رو بیارم بالا ولی نصب کننده اصلا نمیاد.
> آدرس رو که میزنم صفحه سفید میاد

خطای کنسول مرورگر و لاگ
php
رو جهت بررسی بفرستین

**Comment by yoosefap** [comment]
همچنین برای اطمینان می‌تونید قالب نصب کننده رو در مسیر زیر build کنید
`apps/com_pinoox_installer/theme/magic`

داخل ترمینال دستورات زیر رو اجرا کنید
`npm i`
`npm run release`

**Comment by RezaT1994** [comment]
> > من میخوام روی لوکال هاست پینوکس رو بیارم بالا ولی نصب کننده اصلا نمیاد.
> > آدرس رو که میزنم صفحه سفید میاد
> 
> خطای کنسول مرورگر و لاگ
> php
> رو جهت بررسی بفرستین

هیج اروری توی کنسول نیست
همچنین توی php

**Comment by RezaT1994** [comment]
> همچنین برای اطمینان می‌تونید قالب نصب کننده رو دوباره در مسیر زیر بیلد کنید
> `apps/com_pinoox_installer/theme/magic`
> 
> داخل ترمینال دستورات زیر رو اجرا کنید
> `cd {path}/apps/com_pinoox_installer/theme/magic`
> `npm i`
> `npm run release`

انجام دادم ولی هنوز صفحه سفیده

**Comment by yoosefap** [comment]
لطفاً یک اسکرین شات از کنسول مرورگر هم بفرستید

همچنین بعد از اون پینوکس رو از سایت 
pinoox.com
 دریافت کنید ببینید اونجا هم همین مشکل رو دارید

**Comment by RezaT1994** [comment]
![Screenshot from 2020-09-26 11-12-39](https://user-images.githubusercontent.com/31609638/94335554-434ffd80-ffe9-11ea-82a9-5d5692c796ce.png)

هم از سایت دانلود کردم و هم از گیتهاب. هر دو همین مشکل رو دارن

**Comment by yoosefap** [comment]
از چه نسخه php استفاده می‌کنید؟

**Comment by RezaT1994** [comment]
این ارور رو میده

```Warning: Invalid argument supplied for foreach() in /~/pinoox/pincore/boot/loader.php on line 50```

متغیر
`$services`
رو چاپ کردم داره نال میده

**Comment by yoosefap** [comment]
لطفا یک اسکرین شات از هر دو فایل زیر برای ما بفرستید این مشکل متاسفانه گویا فقط در سیستم شما است
`pincore/config/service.config.php `
`pincore/pinker/config/service.config.php `

ممنون که ما را در بررسی این مشکل همراهی می‌کنید
همچنین برای بررسی دقیقتر این موضوع مشخصات لوکال هاست و نسخه 
php 
که استفاده می کنید را اعلام کنید

**Comment by RezaT1994** [comment]
![Screenshot from 2020-09-28 07-21-32](https://user-images.githubusercontent.com/31609638/94388946-4ec33600-015b-11eb-8806-891b6bbe4fe7.png)

مشخصات لوکال هاست
```
OS: Ubuntu 20.04
PHP: 7.4.3
Apache: 2.4.41
MySql: 8.0.21
```

در ضمن اصلا پوشه
pinker
وجود نداره توی ریپازیتوری

**Comment by yoosefap** [comment]
درود لطفا اگر به تلگرام دسترسی دارید به ایدی من پیام بدین تا به کمک هم این مشکل را بررسی کنیم
t.me/yoosefap

**Comment by RezaT1994** [comment]
مشکل برطرف شد. به این صورت

```
sudo chmod 777 /www/pinoox
sudo chmod 777 /www/pinoox/pincore
```

و فعال کردن mod_rewrite روی وب سرور
